version: '3.8'  # ✅ Optional in newer versions

services:
  playwright-test:
    build: .
    command: ["npx", "playwright", "test", "--shard=1/2"]
    environment:
      - BASE_URL=https://www.gov.uk
      - DOCKER=true
    volumes:
      - ./playwright-report:/app/playwright-report  # ✅ Ensures reports persist