jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: sudo apt update && sudo apt install docker-compose -y  # ✅ Ensures Docker Compose is installed

      - name: Start Docker Compose Services
        run: docker compose up --scale playwright-test=2 --abort-on-container-exit