name: Playwright Tests CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # ✅ Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t playwright-tests .

      - name: Run Playwright Tests in Docker
        run: docker run --rm -v ${{ github.workspace }}/playwright-report:/app/playwright-report playwright-tests

      - name: Ensure Report Folder Exists
        run: mkdir -p playwright-report  # ✅ Creates the report folder if missing

      - name: Upload Playwright Test Report
        uses: actions/upload-artifact@v4
        with:
          name: Playwright-Test-Report
          path: playwright-report/