name: Playwright Tests CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Start Docker Compose Services
        run: docker compose up --scale playwright-test=2 --abort-on-container-exit  # ✅ Changed from `docker-compose` to `docker compose`

      - name: Upload Playwright Test Report
        uses: actions/upload-artifact@v4
        with:
          name: Playwright-Test-Report
          path: playwright-report/